apiVersion: v1
kind: Service
metadata:
  name: fastapi-skeleton-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-skeleton
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000